### ISSUE TITLE
Performance of OOD generalizable GNNs

### ISSUE THREAD

**Issue by LFhase** [sadmanomee/OOD_Materials_Benchmark#1]
Hi, thank you for this very interesting and insightful benchmark!

I am wondering would you have any plans to experiment with OOD generalizable GNNs, such as [CIGA](https://github.com/LFhase/CIGA) and [GALA](https://github.com/LFhase/GALA), along with the methods evaluated in [GOOD](https://github.com/divelab/GOOD) benchmark from Prof. Shuiwang Ji's group? It would be helpful to the community to better understand the challenges in OOD materials property prediction! 

Best regards,
Yongqiang Chen

**Comment by sadmanomee** [comment]
Hi Yongqiang,

Thank you for your encouraging words and insightful suggestions regarding our benchmark study. We are indeed intrigued by the idea of experimenting with OOD generalizable GNNs such as CIGA and GALA, as well as the methods evaluated in the GOOD benchmark from Prof. Shuiwang Ji's group. Your proposal aligns well with our ongoing efforts to deepen the understanding of challenges in OOD materials property prediction. We appreciate your contribution to this discourse and plan to incorporate these ideas into our future research endeavors. We believe that exploring these models will significantly enhance the community's grasp of OOD prediction complexities. We look forward to potentially collaborating or sharing insights on this front, especially on incorporating ideas from OOD generalizable GNNs to devise a new GNN for OOD materails property prediction.

Regards,
Sadman Sadeed Omee

**Comment by LFhase** [comment]
Hi Sadman,

It's exciting to learn that you are also pursuing the same as us! We are also looking forward to incorporating insights from different (scientific) scenarios with various graph distribution shifts, to better improve the OOD generalization of GNNs. Let's keep in touch and see if there's any possibility to collaborate on sth.!

Cheers, 
Yongqiang

**Comment by sadmanomee** [comment]
Hi Yongqiang,

Thank you very much. Really looking forward to the collaboration opportunity.

Regards,
Sadman
